version: '3.8'
services: 
  portfolio-website:
    container_name: portfolio-website-container
    image: portfolio-website-img
    build:
      context: .
    ports:
      - 14200:80
    expose:
      - 80