name: Github Pages Deploy

on:
  push:
    branches: ["main", "deploy-pipeline"]

  
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/browser/portfolio-website
        enable_jekyll: true

    # - name: Setup Pages
    #   uses: actions/configure-pages@v4

    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: . #upload entire repo

    # - name:
    #   id: deployment
    #   uses: actions/deploy-pages@v4